// Copyright (c) Alpaca Core
// SPDX-License-Identifier: MIT
//
#pragma once

#define ACLP_FOO_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define ACLP_FOO_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define ACLP_FOO_VERSION_PATCH @PROJECT_VERSION_PATCH@
#define ACLP_FOO_VERSION_TAG "@PROJECT_VERSION_TAG@"

#define ACLP_FOO_VERSION_STRING "@PROJECT_VERSION@@PROJECT_VERSION_TAG@"
